# Generated by Django 3.0.4 on 2020-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='uploaded_Img',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='blur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gaussianNoise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
