# Generated by Django 3.0.4 on 2020-03-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20200322_0736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Image',
        ),
    ]
