# Generated by Django 3.0.4 on 2020-03-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20200322_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augmented_image', models.ImageField(upload_to='augmenteed_images/')),
                ('original_image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
    ]
