# Generated by Django 3.0.4 on 2020-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_augmentedimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_temperature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='grayscale',
            field=models.BooleanField(default=False),
        ),
    ]
