# Generated by Django 3.0.4 on 2020-03-25 06:26

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20200324_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCR', models.FileField(upload_to='ocr/', verbose_name=image.models.Image)),
                ('original_image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
    ]
