# Generated by Django 3.0.4 on 2020-03-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_ocr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCR',
        ),
    ]
